project_id = "xxufxmjlnzfutcffcikv"

[functions.send-mfa-code]
verify_jwt = false

[functions.verify-mfa]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.chat-proxy]
verify_jwt = false

[functions.get-partners]
verify_jwt = false
